migrate-up:
	migrate -path db/migration -database "mysql://pratik:password@tcp(localhost:3306)/basic?charset=utf8&parseTime=True&loc=Local" -verbose up

migrate-down:
	migrate -path db/migration -database "mysql://pratik:password@tcp(localhost:3306)/basic?charset=utf8&parseTime=True&loc=Local" -verbose down